### ISSUE TITLE
TDD - Add quotes & references

### ISSUE THREAD

**Issue by valentinajemuovic** [techexcellenceio/knowledge-base#3]
@JBonifay, some minor notes:

1. Could you add any references for text from other authors, e.g. "You’re not allowed to write any production code until you’ve got a unit test failing first" by Uncle Bob, to put in quotation marks and reference it. That was just one sentence I noted, could you check remainder of document, to put quotes and author around any text.
2. Could you also add references to any source pages. For example, in the section "Test FIRST" - I assume you wrote it by looking at some existing pages, could you reference them...

Thanks in advance!

**Comment by valentinajemuovic** [comment]
I now added examples of referencing here https://github.com/techexcellenceio/knowledge-base/blob/main/CONTRIBUTING.md

**Comment by JBonifay** [comment]
Perfect ! thanks
